spring:
  application:
    name: api-gateway-estudo
  cloud:
    gateway:
      routes:
        # Rotas para API docs - SEM filtros!
        - id: book-service-openapi
          uri: lb://BOOK-SERVICE-ESTUDO
          predicates:
            - Path=/book-service/v3/api-docs
          order: 1

        - id: exchange-service-openapi
          uri: lb://EXCHANGE-SERVICE-ESTUDO
          predicates:
            - Path=/exchange-service/v3/api-docs
          order: 1

        # Rotas genéricas dos serviços
        - id: book-service
          uri: lb://BOOK-SERVICE-ESTUDO
          predicates:
            - Path=/book-service/**
#          filters:
#            - RewritePath=/book-service/(?<segment>.*), /$\{segment}
          order: 2

        - id: exchange-service
          uri: lb://EXCHANGE-SERVICE-ESTUDO
          predicates:
            - Path=/exchange-service/**
#          filters:
#            - RewritePath=/exchange-service/(?<segment>.*), /$\{segment}
          order: 2
  management:
    tracing:
      sampling:
        probability: 1.0
  zipkin:
    base-url: http://localhost:9411

server:
  port: 9000

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: book-service
        url: /book-service/v3/api-docs
      - name: exchange-service
        url: /exchange-service/v3/api-docs

#spring:
#  application:
#    name: api-gateway-estudo
#  cloud:
#    gateway:
#      routes:
#        - id: book-service
#          uri: lb://BOOK-SERVICE-ESTUDO
#          predicates:
#          - Path=/book-service/**
#          filters:
#          - RewritePath=/book-service/(?<segment>.*), /$\{segment}
#
##        - id: book-service-swagger
##          uri: lb://BOOK-SERVICE-ESTUDO
##          predicates:
##            - Path=/book-service/v3/api-docs
##          filters:
##            - RewritePath=/book-service/(?<segment>.*), /$\{segment}
#
#        - id: exchange-service
#          uri: lb://EXCHANGE-SERVICE-ESTUDO
#          predicates:
#            - Path=/exchange-service/**
#          filters:
#            - RewritePath=/exchange-service/(?<segment>.*), /$\{segment}
#
##        - id: exchange-service-swagger
##          uri: lb://EXCHANGE-SERVICE-ESTUDO
##          predicates:
##            - Path=/exchange-service/v3/api-docs
##          filters:
##            - RewritePath=/exchange-service/(?<segment>.*), /$\{segment}
#
#
#          #        - id: book-service
##          uri: lb://BOOK-SERVICE-ESTUDO
##          predicates:
##            - Path=/book-service/**
##          filters:
##            - RewritePath=/book-service(?<segment>/?.*), /book-service/${segment}
##            - RewritePath=/book-service/v3/api-docs, /v3/api-docs
#
##        - id: exchange-service
##          uri: lb://EXCHANGE-SERVICE-ESTUDO
##          predicates:
##            - Path=/exchange-service/**
##          filters:
##            - RewritePath=/exchange-service(?<segment>/?.*), /exchange-service/${segment}
##            - RewritePath=/exchange-service/v3/api-docs, /v3/api-docs
#
#server:
#  port: 9000
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    config-url: /v3/api-docs/swagger-config
#    urls:
#      - name: book-service
#        url: /book-service/v3/api-docs
#      - name: exchange-service
#        url: /exchange-service/v3/api-docs
#  api-docs:
#    enabled: true